blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/Jwuthri/ai-safety-eval-dash/discussions
    about: Ask questions, share ideas, and connect with the community
  - name: 📚 Documentation
    url: https://github.com/Jwuthri/ai-safety-eval-dash/blob/main/README.md
    about: Check out our documentation for guides and API references
  - name: 🚀 Roadmap
    url: https://github.com/Jwuthri/ai-safety-eval-dash/projects
    about: See what we're working on and what's planned for the future
  - name: 🔒 Private Security Report
    url: https://github.com/Jwuthri/ai-safety-eval-dash/security/advisories/new
    about: Report sensitive security vulnerabilities privately
